name: Terraform S3 Lab Pipeline


on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: labs/lab2-s3-bucket

      - name: Terraform Validate
        run: terraform validate
        working-directory: labs/lab2-s3-bucket
